# Generated by Django 5.1.3 on 2024-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('clasificacion', models.CharField(blank=True, max_length=50)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
